version: "2"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: jsontimer
      MYSQL_USER: jsontimer
      MYSQL_PASSWORD: jsontimer
    ports:
      - ${MYSQL_PORT}:3306

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: jsontimer
      PMA_PASSWORD: jsontimer
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - ${PHPMYADMIN_PORT}:80
