version: "2"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: jsontimer
      MYSQL_USER: jsontimer
      MYSQL_PASSWORD: jsontimer

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: jsontimer
      PMA_PASSWORD: jsontimer
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - 8081:80

  redis:
    image: redis:alpine

  node:
    image: node:6
    volumes:
    - ./:/app
    working_dir: /app
    entrypoint: node index.js
    ports:
      - 8080:8080
